# Generated by Django 4.2.1 on 2023-05-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regitraer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleCode', models.CharField(max_length=255)),
                ('totalMarks', models.CharField(max_length=255)),
                ('examType', models.CharField(max_length=255)),
                ('programName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.programreg')),
            ],
        ),
    ]
