# Generated by Django 4.2.1 on 2023-05-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regitraer', '0002_regnumber_alter_student_registrtionno'),
        ('teacher', '0002_alter_exam_programname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1', models.CharField(max_length=255)),
                ('test_2', models.CharField(max_length=255)),
                ('quize_1', models.CharField(max_length=255)),
                ('quize_2', models.CharField(max_length=255)),
                ('attendance', models.CharField(max_length=255)),
                ('moduleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.courseregitration')),
                ('registrationNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.regnumber')),
            ],
        ),
    ]
