# Generated by Django 4.2.1 on 2023-05-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regitraer', '0002_regnumber_alter_student_registrtionno'),
        ('teacher', '0003_caresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='caresult',
            name='registrationNo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='regitraer.regnumber'),
        ),
    ]
