# Generated by Django 4.2.1 on 2023-05-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_caresult_id_alter_caresult_registrationno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresult',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
