# Generated by Django 4.2.1 on 2023-05-27 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_caresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
