# Generated by Django 4.2.1 on 2023-05-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('caMarks', models.CharField(max_length=200)),
                ('finalMarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Bachelor Degree', 'Bachelor Degree'), ('DIPLOMA', 'DIPLOMA')], max_length=200)),
                ('durations', models.CharField(max_length=200)),
                ('semisterNo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.programreg')),
                ('registrtionNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regitraer.regnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultTypes', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('claim', models.TextField(blank=True, null=True)),
                ('evidenceFile', models.ImageField(blank=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.courseregitration')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.programreg')),
            ],
        ),
        migrations.AddField(
            model_name='courseregitration',
            name='programName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.programreg'),
        ),
    ]
