# Generated by Django 4.2.1 on 2023-05-27 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramReg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Bachelor Degree', 'Bachelor Degree'), ('DIPLOMA', 'DIPLOMA')], max_length=200)),
                ('durations', models.CharField(max_length=200)),
                ('semisterNo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=200)),
                ('registrtionNo', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.programreg')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('caMarks', models.CharField(max_length=200)),
                ('finalMarks', models.CharField(max_length=200)),
                ('programName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regitraer.programreg')),
            ],
        ),
    ]
