# Generated by Django 4.2.1 on 2023-05-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regitraer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='registrtionNo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regitraer.regnumber'),
        ),
    ]
